<?php
	include('Scope.php');
	include('Tag.php');
	include('TagShow.php');
	include('TagRepeat.php');
	include('TagExtend.php');
	include('TagIf.php');
	include('TagC.php');
	include('WordTemplate.php');
	include('StringPos.php');
	include('TomateTemplate.php');
?>